{
 "title": "Observability Lab",
 "description": "Monitor Flask application through custom StatsD metrics with Prometheus and Grafana.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total{instance=\"$instance\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{instance=\"$instance\"}/flask_http_request_duration_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{instance=\"$instance\", status=~\"2.*\"}) by(endpoint, method) / sum(flask_http_request_total{instance=\"$instance\"}) by(endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{instance=\"$instance\", status=~\"4.*\"}) by(endpoint, method) / sum(flask_http_request_total{instance=\"$instance\"}) by(endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{instance=\"$instance\"} / flask_http_request_duration_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}